name: Apply patch from comment

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    if: startsWith(github.event.comment.body, '/apply')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract diff block to file
        run: |
          python - << 'PY'
          import os, re, sys, pathlib
          body = os.environ['BODY']
         m = re.search(r'```diff\s*(.*?)```', body, re.S|re.M)

          if not m:
            print("::error::No ```diff``` block found. Start your comment with /apply and include a fenced ```diff block.")
            sys.exit(1)
          pathlib.Path('/tmp/ai.patch').write_text(m.group(1), encoding='utf-8')
          print("Wrote /tmp/ai.patch")
          PY
        env:
          BODY: ${{ github.event.comment.body }}
          - uses: actions/checkout@v4
  with:
    fetch-depth: 0


      - name: Apply patch
        run: |
          git config user.name "itstitanium-bot"
          git config user.email "bot@users.noreply.github.com"
          git apply --whitespace=fix /tmp/ai.patch

      - name: Commit & push
        run: |
          BRANCH="ai/update-${{ github.run_id }}"
          git checkout -b "$BRANCH"
          git add -A
          git commit -m "AI patch from comment ${{ github.event.comment.html_url }}"
          git push -u origin "$BRANCH"

      - name: Open PR
        uses: peter-evans/create-pull-request@v6
        with:
          title: "AI patch ${{ github.run_id }}"
          body: "Applied patch from: ${{ github.event.comment.html_url }}"
          base: main
          head: ai/update-${{ github.run_id }}
