name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Start static server
        run: |
          npx --yes http-server ./public -p 4173 -c-1 > /tmp/http-server.log 2>&1 &
          echo $! > /tmp/http-server.pid
          sleep 3

      - name: Align content
        run: npm run align

      - name: HTML validation
        run: npx --yes html-validate "public/**/*.html"

      - name: Link check (lychee)
        run: |
          cargo install lychee
          lychee --no-progress --accept 200,301,302,308 public/**/*.html

      - name: Lighthouse CI
        run: npx --yes @lhci/cli autorun --collect.url=http://localhost:4173/index.html --collect.numberOfRuns=3 --upload.target=temporary-public-storage

      - name: Accessibility - pa11y
        run: npx --yes pa11y http://localhost:4173/index.html --standard WCAG2AA

      - name: Accessibility - axe
        run: npx --yes @axe-core/cli http://localhost:4173/index.html

      - name: JSON sanity checks
        run: node scripts/json-sanity.js

      - name: Speakable and blog addendum checks
        run: node scripts/check-speakable.js

      - name: Affiliate rel guardrail
        run: node scripts/check-affiliate-rel.js

      - name: Guardrail - domain typo
        run: |
          if grep -R "https://itstitaniun.com" public; then
            echo "Found incorrect domain references" >&2
            exit 1
          fi

      - name: Validate sitemap
        if: exists('public/sitemap.xml')
        run: xmllint --noout public/sitemap.xml

      - name: Stop server
        if: always()
        run: |
          if [ -f /tmp/http-server.pid ]; then
            kill $(cat /tmp/http-server.pid) || true
          fi
          if [ -f /tmp/http-server.log ]; then
            cat /tmp/http-server.log
          fi
