name: Make TLDR Audio

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-audio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install espeak and ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y espeak ffmpeg

      - name: Ensure audio directory
        run: mkdir -p public/assets/audio

      - name: Write transcript text
        shell: bash
        run: |
          printf '%s\n' 'Use medium heat, avoid aerosol oils, hand-wash after the pan cools, and use silicone or wood tools. Check your model'\''s oven and induction labels, then store with protectors.' > tldr.txt

      - name: Synthesize WAV with espeak
        run: |
          espeak -v en-us -s 165 -a 180 -w public/assets/audio/titanium-guide-tldr.wav -f tldr.txt

      - name: Convert to MP3 and OGG
        run: |
          ffmpeg -y -i public/assets/audio/titanium-guide-tldr.wav -codec:a libmp3lame -q:a 2 public/assets/audio/titanium-guide-tldr.mp3
          ffmpeg -y -i public/assets/audio/titanium-guide-tldr.wav -codec:a libvorbis -qscale:a 5 public/assets/audio/titanium-guide-tldr.ogg
          rm public/assets/audio/titanium-guide-tldr.wav tldr.txt

      - name: Commit audio files
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
        run: |
          git add public/assets/audio/titanium-guide-tldr.*
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Add/Update TLDR audio (MP3/OGG)"
            git push
          fi
